// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WingetMaintainer.Data;

#nullable disable

namespace WingetMaintainer.Data.Migrations
{
    [DbContext(typeof(WingetMaintainerDbContext))]
    partial class WingetMaintainerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WingetMaintainer.Data.Entities.Package", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("With")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("WingetMaintainer.Data.Entities.PackageRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageIdentifier");

                    b.ToTable("PackageRuns");
                });

            modelBuilder.Entity("WingetMaintainer.Data.Entities.StateEntry", b =>
                {
                    b.Property<string>("PackageIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallerHashes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PackageIdentifier");

                    b.ToTable("StateEntries");
                });

            modelBuilder.Entity("WingetMaintainer.Data.Entities.ValidationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageIdentifier");

                    b.HasIndex("PackageRunId");

                    b.HasIndex("Status");

                    b.ToTable("ValidationJobs");
                });

            modelBuilder.Entity("WingetMaintainer.Data.Entities.ValidationJob", b =>
                {
                    b.HasOne("WingetMaintainer.Data.Entities.PackageRun", "PackageRun")
                        .WithMany("ValidationJobs")
                        .HasForeignKey("PackageRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageRun");
                });

            modelBuilder.Entity("WingetMaintainer.Data.Entities.PackageRun", b =>
                {
                    b.Navigation("ValidationJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
