name: Sonar

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: "install dependencies and test"
        run : |
          Install-Module -Name PSScriptAnalyzer -Force
          # Test if the analyzer is correctly installed
          Invoke-ScriptAnalyzer -ScriptDefinition '"b" = "b"; function eliminate-file () { }'
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.ps.plugin.skip=false
            -Dsonar.ps.tokenizer.skip=false
            -Dsonar.projectKey=winget-pgks-updatepipelines

