name: Add GitHub Package

on:
  workflow_dispatch:
    inputs:
      packageId:
        description: 'winget PackageId'
        required: true
      forceAdd:
        description: 'Force add package even if no new version is detected'
        type: boolean
        required: false
        default: false
      resolves: 
        description: 'resolves this issues - if set it will be auto submitted'
        required: false
      With:
        required: true
        type: choice
        description: 'WinGetCreate or komac'
        default: 'komac'
        options:
        - komac
        - WinGetCreate

permissions:
  contents: read

jobs:
  script:
    name: ${{ inputs.packageId }}
    runs-on: windows-2025
    env:
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
    steps:
      - name: create App token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true
      - name: Update package
        shell: pwsh
        run: |
          Import-Module .\modules\WingetMaintainerModule
          $params = @{
            PackageId = $env:INPUTS_PACKAGEID
            forceAdd  = [System.Convert]::ToBoolean($env:INPUTS_FORCEADD)
            With      = $env:INPUTS_WITH
          }
          if (-not [string]::IsNullOrWhiteSpace($env:INPUTS_RESOLVES)) {
            $params.resolves = $env:INPUTS_RESOLVES
          }
          .\scripts\Add-GitHubPackage.ps1 @params
        env:
          INPUTS_PACKAGEID: ${{ inputs.packageId }}
          INPUTS_RESOLVES: ${{ inputs.resolves }}
          INPUTS_FORCEADD: ${{ inputs.forceAdd }}
          INPUTS_WITH: ${{ inputs.With }}
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "Add GitHub Package: ${{ inputs.packageId }}"
          file_pattern: ./github-releases-monitored.yml
