name: Run Get-MSIFileInformation

on:
  workflow_dispatch:
    inputs:
      websiteURL:
        description: 'MSI Installer URL'
        required: true

permissions:
  contents: read

jobs:
  run-msi-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run Get-MSIFileInformation
        run: |
          $WebsiteURL = '$env:GITHUB_EVENT_INPUTS_WEBSITEURL'
          Import-Module .\modules\WingetMaintainerModule\Public\Get-MSIFileInformation.ps1
          Get-MSIFileInformation -WebsiteURL $WebsiteURL
        shell: pwsh
        env:
          GITHUB_EVENT_INPUTS_WEBSITEURL: ${{ github.event.inputs.websiteURL }}
