name: Run Get-MSIFileInformation

on:
  workflow_dispatch:
    inputs:
      websiteURL:
        description: 'MSI Installer URL'
        required: true

jobs:
  run-msi-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Get-MSIFileInformation
        run: |
          $WebsiteURL = '${{ github.event.inputs.websiteURL }}'
          Import-Module .\modules\WingetMaintainerModule\Public\Get-MSIFileInformation.ps1
          Get-MSIFileInformation -WebsiteURL $WebsiteURL
        shell: pwsh
