name: Cleanup Branches
on:
  workflow_dispatch:
  schedule:
    - cron:  '3 12 * * *'

permissions: {}

jobs:
  komac-cleanup:
       name: cleanup branches
       runs-on: ubuntu-latest
       steps:
       - name: Run Komac
         uses: b0t-at/run-komac@e5e74ed265cc67a27ce04c428255c40e549ade59
         with:
            args: 'cleanup --token=${{ secrets.WINGET_PAT }}'
            custom-fork-owner: damn-good-b0t
