name: Cleanup Branches
on:
  workflow_dispatch:
  schedule:
    - cron:  '3 12 * * *'

permissions: {}

jobs:
  komac-cleanup:
       name: cleanup branches
       runs-on: ubuntu-latest
       steps:
       - name: Run Komac
         uses: michidk/run-komac@9b27eadc6e9235c252444a437d246c139da2f57f # v2.1.0
         with:
            args: 'cleanup --token=${{ secrets.WINGET_PAT }}'
            custom-fork-owner: damn-good-b0t
