name: Orchestrate GH Packages
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - github-releases-monitored.yml
jobs:
    update-package-count:
        runs-on: ubuntu-latest

        permissions:
            contents: write
        steps:
            - name: create App token
              uses: actions/create-github-app-token@v2
              id: app-token
              with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.PRIVATE_KEY }}
            - name: Check out code
              uses: actions/checkout@v5
              with:
                token: ${{ steps.app-token.outputs.token }}
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: pip install pyyaml ruamel.yaml
            - name: Count packages
              id: count
              run: |
                python3 scripts/orchestrate_gh-packages.py
                git status
            - name: Commit and push
              uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
              with:
                commit_message: Update package count badge
                file_pattern: |
                  .github/workflows/update-github-packages-*.yml
