name: Rebuild Package Manifests
on:
  workflow_dispatch:
    inputs:
      PackageIdentifier:
        description: "Package Identifier"
        required: true
      submit:
        description: 'True to auto-submit'
        required: true
        type: boolean
        default: false
      resolves: 
        description: 'resolves this issues'
        required: false
        default: ''
jobs:
  update:
    name: Rebuild manifests
    runs-on: windows-2025
    env:
      WINGET_PKGS_FORK_REPO: ${{vars.WINGET_PKGS_FORK_REPO}}
      GITHUB_TOKEN: ${{ secrets.WINGET_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Trigger Mass Package Update
        run: |
          $fullPathFork = "$(Get-Location)"
          $resolves = $env:GITHUB_EVENT_INPUTS_RESOLVES
          scripts/Update-AllPackageManifests.ps1 -PackageIdentifier $env:GITHUB_EVENT_INPUTS_PACKAGEIDENTIFIER -OutputDir $fullPathFork -Token $env:GITHUB_TOKEN -Submit $env:GITHUB_EVENT_INPUTS_SUBMIT ( ![string]::IsNullOrWhitespace($resolves) ? "-Resolves  $resolves" : $null )
        env:
          GITHUB_EVENT_INPUTS_RESOLVES: ${{ github.event.inputs.resolves }}
          GITHUB_EVENT_INPUTS_PACKAGEIDENTIFIER: ${{ github.event.inputs.PackageIdentifier }}
          GITHUB_EVENT_INPUTS_SUBMIT: ${{ github.event.inputs.submit }} 
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: manifests
          path: manifests
