name: Screenshot with Virtual Display

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Screen Capture Recorder
        shell: powershell
        run: |
          # Create directory for downloads
          New-Item -ItemType Directory -Path ".\downloads" -Force
          
          # Download Screen Capture Recorder installer
          $installerUrl = "https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/download/v0.13.3/Setup.Screen.Capturer.Recorder.v0.13.3.exe"
          $installerPath = ".\downloads\scr_installer.exe"
          
          Write-Host "Downloading Screen Capture Recorder..."
          Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath -UseBasicParsing
          
          # Install silently
          Write-Host "Installing Screen Capture Recorder..."
          Start-Process -FilePath $installerPath -ArgumentList "/VERYSILENT" -Wait
          
          # Allow time for drivers to register
          Write-Host "Waiting for installation to complete..."
          Start-Sleep -Seconds 10
          
          Write-Host "Screen Capture Recorder installed successfully"

      - name: Take screenshot using FFmpeg
        shell: powershell
        run: |
          # Download portable FFmpeg
          $ffmpegUrl = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
          $ffmpegZip = ".\downloads\ffmpeg.zip"
          
          Write-Host "Downloading FFmpeg..."
          Invoke-WebRequest -Uri $ffmpegUrl -OutFile $ffmpegZip -UseBasicParsing
          
          # Extract FFmpeg
          Write-Host "Extracting FFmpeg..."
          Expand-Archive -Path $ffmpegZip -DestinationPath ".\ffmpeg" -Force
          
          # Find the ffmpeg.exe path
          $ffmpegExe = Get-ChildItem -Path ".\ffmpeg" -Recurse -Filter "ffmpeg.exe" | Select-Object -First 1 -ExpandProperty FullName
          
          # Use FFmpeg to capture screen
          Write-Host "Capturing screenshot with FFmpeg..."
          & $ffmpegExe -f gdigrab -framerate 1 -i desktop -frames:v 1 screenshot.png
          
          # Verify screenshot was created
          if (Test-Path "screenshot.png") {
            Write-Host "Screenshot captured successfully"
          } else {
            Write-Error "Screenshot capture failed"
            exit 1
          }
      
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: virtual-display-screenshots
          path: screenshot.png
          retention-days: 5